### ISSUE TITLE
NPE from TestFairy session - Transaction.getRequest()' on a null object reference

### ISSUE THREAD

**Issue by atsakiridis** [RestComm/restcomm-android-sdk#358]
Unfortunately there are no logs at the time of the crash to figure out what was going on although it is clear from the initial logs that Olympus doesn't manage to register with Restcomm due to java.io.IOException: Could not connect to /182.180.81.76:5080. Also, the App crashed almost 1 hour after being put in the background. 

Exception is:
```
java.lang.NullPointerException: Attempt to invoke interface method 'android.javax.sip.message.Request android.javax.sip.Transaction.getRequest()' on a null object reference
	at org.mobicents.restcomm.android.client.sdk.SignalingClient.JainSipClient.JainSipJobManager.getByCallId(JainSipJobManager.java:71)
	at org.mobicents.restcomm.android.client.sdk.SignalingClient.JainSipClient.JainSipClient$3.run(JainSipClient.java:686)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.os.HandlerThread.run(HandlerThread.java:61)
```

Which suggests that a SIP response is received for some previous request (most likely REGISTER, but without logs I can't be sure), and for the related job the SIP transaction is null, which I can't explain. Also there shouldn't be any SIP response, since the REGISTER messages all fail due to transport issues.

Let's keep this open for now and see if it pops up again. I will also try to tell TF to collect long for longer period (i.e. 24 hours)

TestFairy session:
https://telestax.testfairy.com/projects/1897533-restcommolympus/builds/3980986/sessions/56

P.S. Notice that this has occurred a couple of times for different devices, but in all of them it happens long after the App has been backgrounded

**Comment by atsakiridis** [comment]
Closing for now as its no longer reproducible
