### ISSUE TITLE
Runtime exception - Error receiving broadcast Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4000010 (has extras) } 

### ISSUE THREAD

**Issue by atsakiridis** [RestComm/restcomm-android-sdk#360]
Seems that while in the background after long period of time (~ 2 and half hours) a connectivity change occurs (probably network getting connected as I see that we are trying to bind in the signaling facilities) that somehow breaks the App -notice that Wifi is being used. From the stack trace it seems that we are using TLS:

```
java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4000010 (has extras) } in org.mobicents.restcomm.android.client.sdk.SignalingClient.JainSipClient.JainSipNotificationManager@42f1e400
	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java)
	at android.os.Handler.handleCallback(Handler.java)
	at android.os.Handler.dispatchMessage(Handler.java)
	at android.os.Looper.loop(Looper.java)
	at android.os.HandlerThread.run(HandlerThread.java)
Caused by: java.lang.RuntimeException: Failed to set up networking facilities
	at org.mobicents.restcomm.android.client.sdk.SignalingClient.JainSipClient.JainSipClient.jainSipClientBind(JainSipClient.java:414)
	at org.mobicents.restcomm.android.client.sdk.SignalingClient.JainSipClient.JainSipJob$JainSipFsm.process(JainSipJob.java:631)
	at org.mobicents.restcomm.android.client.sdk.SignalingClient.JainSipClient.JainSipJob.startFsm(JainSipJob.java:742)
	at org.mobicents.restcomm.android.client.sdk.SignalingClient.JainSipClient.JainSipJobManager.add(JainSipJobManager.java:29)
	at org.mobicents.restcomm.android.client.sdk.SignalingClient.JainSipClient.JainSipJobManager.add(JainSipJobManager.java:37)
	at org.mobicents.restcomm.android.client.sdk.SignalingClient.JainSipClient.JainSipClient.onConnectivityChange(JainSipClient.java:870)
	at org.mobicents.restcomm.android.client.sdk.SignalingClient.JainSipClient.JainSipNotificationManager.onReceive(JainSipNotificationManager.java:110)
	... 5 more
Caused by: android.javax.sip.InvalidArgumentException: bind failed: EADDRINUSE (Address already in use)
	at android.gov.nist.javax.sip.SipStackImpl.createListeningPoint(SipStackImpl.java:1624)
	at org.mobicents.restcomm.android.client.sdk.SignalingClient.JainSipClient.JainSipClient.jainSipClientBind(JainSipClient.java:401)
	... 11 more
Caused by: java.net.BindException: bind failed: EADDRINUSE (Address already in use)
	at libcore.io.IoBridge.bind(IoBridge.java:89)
	at java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150)
	at java.net.ServerSocket.(ServerSocket.java:101)
	at javax.net.ssl.SSLServerSocket.(SSLServerSocket.java:90)
	at com.android.org.conscrypt.OpenSSLServerSocketImpl.(OpenSSLServerSocketImpl.java:58)
	at com.android.org.conscrypt.OpenSSLServerSocketFactoryImpl.createServerSocket(OpenSSLServerSocketFactoryImpl.java:71)
	at android.gov.nist.core.net.SslNetworkLayer.createSSLServerSocket(SslNetworkLayer.java:159)
	at android.gov.nist.javax.sip.stack.TLSMessageProcessor.start(TLSMessageProcessor.java:95)
	at android.gov.nist.javax.sip.SipStackImpl.createListeningPoint(SipStackImpl.java:1612)
	... 12 more
Caused by: libcore.io.ErrnoException: bind failed: EADDRINUSE (Address already in use)
	at libcore.io.Posix.bind(Native Method)
	at libcore.io.ForwardingOs.bind(ForwardingOs.java:40)
	at libcore.io.IoBridge.bind(IoBridge.java:87)
	... 20 more
```

Unfortunately, at that point no logs are collected, so no much more we can tell

Test Fairy session:

https://telestax.testfairy.com/projects/1897533-restcommolympus/builds/3980986/sessions/150

**Comment by atsakiridis** [comment]
Closing for now as its no longer reproducible
