### ISSUE TITLE
Fix crash on SDK

### ISSUE THREAD

**Issue by atsakiridis** [RestComm/restcomm-android-sdk#415]
@desipepova got this crash:

```
java.lang.RuntimeException: SIP transaction error
	at org.restcomm.android.sdk.SignalingClient.JainSipClient.JainSipCall.jainSipCallHangup(JainSipCall.java:233)
	at org.restcomm.android.sdk.SignalingClient.JainSipClient.JainSipCall.disconnect(JainSipCall.java:157)
	at org.restcomm.android.sdk.SignalingClient.JainSipClient.JainSipClient.disconnect(JainSipClient.java:363)
	at org.restcomm.android.sdk.SignalingClient.SignalingHandler.handleMessage(SignalingHandler.java:87)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:194)
	at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by: org.restcomm.android.sdk.SignalingClient.JainSipClient.JainSipException
	at org.restcomm.android.sdk.SignalingClient.JainSipClient.JainSipMessageBuilder.buildByeRequest(JainSipMessageBuilder.java:312)
	at org.restcomm.android.sdk.SignalingClient.JainSipClient.JainSipCall.jainSipCallHangup(JainSipCall.java:217)
	... 6 more
Caused by: android.javax.sip.SipException: Cannot find listening point for transport TLS
	at android.gov.nist.javax.sip.stack.SIPDialog.createRequest(SIPDialog.java:2419)
	at android.gov.nist.javax.sip.stack.SIPDialog.createRequest(SIPDialog.java:2350)
	at org.restcomm.android.sdk.SignalingClient.JainSipClient.JainSipMessageBuilder.buildByeRequest(JainSipMessageBuilder.java:280)
	... 7 more
```

Here's the associated session:

https://app.testfairy.com/projects/3369662-restcommolympus/builds/4345950/sessions/27

**Comment by atsakiridis** [comment]
TF session is empty apart from the crash. Given that we seem to have somehow gotten to an inconsistent state for the BYE generation to fail with 'Cannot find listening point for transport TLS', we need more data. Closing until we manage to reproduce with actual logs.
