### ISSUE TITLE
Improve behaviour when port is already in use

### ISSUE THREAD

**Issue by atsakiridis** [RestComm/restcomm-android-sdk#416]
Maybe show a hard error to the UI?

Right now we are crashing, like:

```
java.lang.RuntimeException: Failed to set up networking facilities
    at org.restcomm.android.sdk.SignalingClient.JainSipClient.JainSipClient.jainSipClientBind(JainSipClient.java:436)
    at org.restcomm.android.sdk.SignalingClient.JainSipClient.JainSipJob$JainSipFsm.process(JainSipJob.java:182)
    at org.restcomm.android.sdk.SignalingClient.JainSipClient.JainSipJob.startFsm(JainSipJob.java:764)
    at org.restcomm.android.sdk.SignalingClient.JainSipClient.JainSipJobManager.add(JainSipJobManager.java:51)
    at org.restcomm.android.sdk.SignalingClient.JainSipClient.JainSipJobManager.add(JainSipJobManager.java:59)
    at org.restcomm.android.sdk.SignalingClient.JainSipClient.JainSipClient.open(JainSipClient.java:201)
    at org.restcomm.android.sdk.SignalingClient.SignalingHandler.handleMessage(SignalingHandler.java:75)
    at android.os.Handler.dispatchMessage(Handler.java:111)
    at android.os.Looper.loop(Looper.java:194)
    at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by: android.javax.sip.InvalidArgumentException: bind failed: EADDRINUSE (Address already in use)
    at android.gov.nist.javax.sip.SipStackImpl.createListeningPoint(SipStackImpl.java:1624)
    at org.restcomm.android.sdk.SignalingClient.JainSipClient.JainSipClient.jainSipClientBind(JainSipClient.java:423)
    ... 9 more
Caused by: java.net.BindException: bind failed: EADDRINUSE (Address already in use)
    at libcore.io.IoBridge.bind(IoBridge.java:104)
    at java.net.PlainSocketImpl.bind(PlainSocketImpl.java:137)
    at java.net.ServerSocket.(ServerSocket.java:105)
    at javax.net.ssl.SSLServerSocket.(SSLServerSocket.java:90)
    at com.android.org.conscrypt.OpenSSLServerSocketImpl.(OpenSSLServerSocketImpl.java:51)
    at com.android.org.conscrypt.OpenSSLServerSocketFactoryImpl.createServerSocket(OpenSSLServerSocketFactoryImpl.java:77)
    at android.gov.nist.core.net.SslNetworkLayer.createSSLServerSocket(SslNetworkLayer.java:159)
    at android.gov.nist.javax.sip.stack.TLSMessageProcessor.start(TLSMessageProcessor.java:95)
    at android.gov.nist.javax.sip.SipStackImpl.createListeningPoint(SipStackImpl.java:1612)
    ... 10 more
Caused by: android.system.ErrnoException: bind failed: EADDRINUSE (Address already in use)
    at libcore.io.Posix.bind(Native Method)
    at libcore.io.ForwardingOs.bind(ForwardingOs.java:56)
    at libcore.io.IoBridge.bind(IoBridge.java:102)
    ... 18 more
```

**Comment by atsakiridis** [comment]
This should be fixed
