### ISSUE TITLE
Olympus sporadically crashes when connectivity is reestablished via Wifi

### ISSUE THREAD

**Issue by atsakiridis** [RestComm/restcomm-android-sdk#419]
Scenario:
- Olympus has remained offline for a long time
- Open Olympus and navigate to the Messages screen
- Enable Wifi via router
- When connectivity is reestablished the app crashes

Apparently, the transaction object is null for some reason when the response to the REGISTER is received on the TYPE_START_NETWORKING job:

```
10-03 11:15:08.961 23128-23162/org.restcomm.android.olympus V/JainSipClient: bind()
10-03 11:15:08.961 23128-23162/org.restcomm.android.olympus V/JainSipClient: getIPAddress()
10-03 11:15:08.992 23128-23162/org.restcomm.android.olympus V/JainSipClient: jainSipRegister()
10-03 11:15:08.993 23128-23162/org.restcomm.android.olympus V/JainSipClient: jainSipRegister(), jobs status: Job count: 2, details: {1475301688713=org.restcomm.android.sdk.SignalingClient.JainSipClient.JainSipJob Object {
	Job Id: 1475301688713
	Type: TYPE_START_NETWORKING
	Transaction: null
	Parameters: {incoming-call-intent=Intent { act=org.restcomm.android.sdk.ACTION_RESUME_CALL flg=0x20000000 cmp=org.restcomm.android.olympus/.CallActivity (has extras) }, turn-username=atsakiridis, signaling-secure=true, pref_sip_user=antonis, pref_proxy_domain=sip:telestax.restcomm.com, turn-url=https://service.xirsys.com/ice, turn-password=4e89a09e-bf6f-11e5-a15c-69ffdcc2b8a7, pref_sip_password=el@m0ynte, turn-enabled=true, connectivity-status=RCConnectivityStatusWiFi, incoming-message-intent=Intent { act=org.restcomm.android.sdk.ACTION_INCOMING_MESSAGE cmp=org.restcomm.android.olympus/.MessageActivity }}
	Fsm: org.restcomm.android.sdk.SignalingClient.JainSipClient.JainSipJob$JainSipFsm Object { Type: TYPE_START_NETWORKING, Index: 1 }
  }, 1475482508961=org.restcomm.android.sdk.SignalingClient.JainSipClient.JainSipJob Object {
	Job Id: 1475482508961
	Type: TYPE_START_NETWORKING
	Transaction: null
	Parameters: {incoming-call-intent=Intent { act=org.restcomm.android.sdk.ACTION_RESUME_CALL flg=0x20000000 cmp=org.restcomm.android.olympus/.CallActivity (has extras) }, turn-username=atsakiridis, signaling-secure=true, pref_sip_user=antonis, pref_proxy_domain=sip:telestax.restcomm.com, turn-url=https://service.xirsys.com/ice, turn-password=4e89a09e-bf6f-11e5-a15c-69ffdcc2b8a7, pref_sip_password=el@m0ynte, turn-enabled=true, connectivity-status=RCConnectivityStatusWiFi, incoming-message-intent=Intent { act=org.restcomm.android.sdk.ACTION_INCOMING_MESSAGE cmp=org.restcomm.android.olympus/.MessageActivity }}
	Fsm: org.restcomm.android.sdk.SignalingClient.JainSipClient.JainSipJob$JainSipFsm Object { Type: TYPE_START_NETWORKING, Index: 0 }
  }}
10-03 11:15:09.005 23128-23162/org.restcomm.android.olympus I/JainSipMessageBuilder: createContactAddress()
10-03 11:15:09.006 23128-23162/org.restcomm.android.olympus I/JainSipMessageBuilder: createUserAgentHeader()
10-03 11:15:09.007 23128-23162/org.restcomm.android.olympus I/JainSipClient: Sending SIP request: 
  REGISTER sip:telestax.restcomm.com SIP/2.0
  Call-ID: ab31d9052f5fe9356b714d58fccdfca5@192.168.2.105
  CSeq: 1 REGISTER
  From: "antonis" <sip:antonis@telestax.restcomm.com>;tag=1475482509005
  To: "antonis" <sip:antonis@telestax.restcomm.com>
  Via: SIP/2.0/TLS 192.168.2.105:5090;rport
  Max-Forwards: 70
  Route: <sip:telestax.restcomm.com;lr>
  Contact: <sip:192.168.2.105:5090;transport=tls;registering_acc=telestax.restcomm.com>
  User-Agent: TelScale Restcomm Android Client 1.0.0-BETA4#1542
  Expires: 60
  Content-Length: 0
10-03 11:15:09.009 23128-23162/org.restcomm.android.olympus V/SignalingHandler: onClientRegisteringEvent: jobId: 1475482508961
10-03 11:15:09.009 23128-23128/org.restcomm.android.olympus I/SignalingClient: handleMessage: type: REGISTERING_EVENT, jobId: 1475482508961
10-03 11:15:09.010 23128-23128/org.restcomm.android.olympus I/RCDevice: onRegisteringEvent(): id: 1475482508961
10-03 11:15:09.746 23128-23188/org.restcomm.android.olympus D/TESTFAIRYSDK: There are 40 files on disk, waiting to be sent
10-03 11:15:09.747 23128-23188/org.restcomm.android.olympus W/System: ClassLoader referenced unknown path: /system/framework/tcmclient.jar
10-03 11:15:11.241 23128-23162/org.restcomm.android.olympus I/JainSipClient: Received SIP response: 
  SIP/2.0 407 Proxy Authentication required
  To: "antonis" <sip:antonis@telestax.restcomm.com>;tag=44505722_f23397de_57a5b08a_dc592bf1
  Via: SIP/2.0/TLS 192.168.2.105:5090;rport=51689;branch=z9hG4bK-373633-2fc03aed600008346d5f3543a90ba259;received=46.177.245.189
  CSeq: 1 REGISTER
  Call-ID: ab31d9052f5fe9356b714d58fccdfca5@192.168.2.105
  From: "antonis" <sip:antonis@telestax.restcomm.com>;tag=1475482509005
  Server: TelScale Restcomm 8.0.0.1363
  Proxy-Authenticate: Digest realm="telestax.restcomm.com",nonce="31373566386263392d333963362d346"
  Content-Length: 0
10-03 11:15:11.301 23128-23162/org.restcomm.android.olympus I/TESTFAIRYSDK: Saved stack trace to /data/user/0/org.restcomm.android.olympus/files/testfairy-stacktrace.38574952-3369662-4386024-46156374-50860a142e8844d8c69e262b257aaf8ef9c1a78c.1475482511300
10-03 11:15:11.301 23128-23162/org.restcomm.android.olympus I/TESTFAIRYSDK: Sending crash {"timestamp":1475482511,"message":"java.lang.NullPointerException: Attempt to invoke interface method 'android.javax.sip.message.Request android.javax.sip.Transaction.getRequest()' on a null object reference","stackTrace":"java.lang.NullPointerException: Attempt to invoke interface method 'android.javax.sip.message.Request android.javax.sip.Transaction.getRequest()' on a null object reference\n\tat org.restcomm.android.sdk.SignalingClient.JainSipClient.JainSipJobManager.getByCallId(JainSipJobManager.java:93)\n\tat org.restcomm.android.sdk.SignalingClient.JainSipClient.JainSipClient$3.run(JainSipClient.java:713)\n\tat android.os.Handler.handleCallback(Handler.java:739)\n\tat android.os.Handler.dispatchMessage(Handler.java:95)\n\tat android.os.Looper.loop(Looper.java:148)\n\tat android.os.HandlerThread.run(HandlerThread.java:61)\n"}
10-03 11:15:11.302 23128-23162/org.restcomm.android.olympus W/System: ClassLoader referenced unknown path: /system/framework/tcmclient.jar
10-03 11:15:11.304 23128-23162/org.restcomm.android.olympus E/AndroidRuntime: FATAL EXCEPTION: signaling-handler-thread
	Process: org.restcomm.android.olympus, PID: 23128
	Theme: themes:{default=overlay:com.cyngn.hexo, iconPack:com.cyngn.hexo, fontPkg:com.cyngn.hexo, com.android.systemui=overlay:com.cyngn.hexo, com.android.systemui.navbar=overlay:com.cyngn.hexo}
	java.lang.NullPointerException: Attempt to invoke interface method 'android.javax.sip.message.Request android.javax.sip.Transaction.getRequest()' on a null object reference
		 at org.restcomm.android.sdk.SignalingClient.JainSipClient.JainSipJobManager.getByCallId(JainSipJobManager.java:93)
		 at org.restcomm.android.sdk.SignalingClient.JainSipClient.JainSipClient$3.run(JainSipClient.java:713)
		 at android.os.Handler.handleCallback(Handler.java:739)
		 at android.os.Handler.dispatchMessage(Handler.java:95)
		 at android.os.Looper.loop(Looper.java:148)
		 at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by atsakiridis** [comment]
I can't reproduce this issue either simulating the scenario and triggering connectivity changes from the device or from the office router. However, it seems that there are two TYPE_START_NETWORKING jobs existing, one created 3 days back and another at the time of the crash. So the most likely event is that when the old job tried to register with Restcomm it failed and the transaction object didn't get set. At the same time, in the exception catch block we don't remove the job and hence the issue
