### ISSUE TITLE
Fix Olympus crash due to java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by atsakiridis** [RestComm/restcomm-android-sdk#432]
Here's the stack trace:

```
java.lang.ArrayIndexOutOfBoundsException: length=3; index=3
	at org.restcomm.android.sdk.SignalingClient.JainSipClient.JainSipJob$JainSipFsm.process(JainSipJob.java:650)
	at org.restcomm.android.sdk.SignalingClient.JainSipClient.JainSipJob.processFsm(JainSipJob.java:787)
	at org.restcomm.android.sdk.SignalingClient.JainSipClient.JainSipClient$3.run(JainSipClient.java:725)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:152)
	at android.os.HandlerThread.run(HandlerThread.java:61)
```
And the TF session is [here](https://telestax.testfairy.com/projects/3369662-restcommolympus/builds/4475020/sessions/23)

**Comment by atsakiridis** [comment]
For now I try to fix it defensively by fixing some cases where a Job that is over is erroneously left alive in the Job container
