### ISSUE TITLE
Lift requirement that video views must always be provided in RCDevice.connect()

### ISSUE THREAD

**Issue by atsakiridis** [RestComm/restcomm-android-sdk#439]
Right now if you call RCDevice.connect() and disable video, but don't pass any video views, the SDK will crash:

```

Crash report for Restcomm Olympus 1.0.0-BETA4 (1563)
Message

java.lang.NullPointerException: Attempt to invoke virtual method 'void org.webrtc.SurfaceViewRenderer.setVisibility(int)' on a null object reference

Stacktrace

java.lang.NullPointerException: Attempt to invoke virtual method 'void org.webrtc.SurfaceViewRenderer.setVisibility(int)' on a null object reference
    at org.restcomm.android.sdk.RCConnection.updateVideoView(RCConnection.java:1237)
    at org.restcomm.android.sdk.RCConnection.access$2000(RCConnection.java:101)
    at org.restcomm.android.sdk.RCConnection$20.run(RCConnection.java:1606)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5343)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
```

**Comment by atsakiridis** [comment]
Fixed with #572
