### ISSUE TITLE
Investigate crash on jainSipClientRegister

### ISSUE THREAD

**Issue by atsakiridis** [RestComm/restcomm-android-sdk#440]
Here's the stacktrace:

```
java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4000010 (has extras) } in org.restcomm.android.sdk.SignalingClient.JainSipClient.JainSipNotificationManager@31d8c37a
    at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:876)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:135)
    at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by: java.lang.IllegalMonitorStateException
    at java.util.concurrent.locks.ReentrantLock$Sync.tryRelease(ReentrantLock.java:122)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.release(AbstractQueuedSynchronizer.java:1238)
    at java.util.concurrent.locks.ReentrantLock.unlock(ReentrantLock.java:428)
    at android.gov.nist.javax.sip.stack.KeyedSemaphore.leaveIOCriticalSection(KeyedSemaphore.java:44)
    at android.gov.nist.javax.sip.stack.NIOHandler.openOutgoingConnection(NIOHandler.java:326)
    at android.gov.nist.javax.sip.stack.NIOHandler.createOrReuseSocket(NIOHandler.java:472)
    at android.gov.nist.javax.sip.stack.NioTcpMessageChannel.(NioTcpMessageChannel.java:192)
    at android.gov.nist.javax.sip.stack.NioTlsMessageChannel.(NioTlsMessageChannel.java:204)
    at android.gov.nist.javax.sip.stack.NioTlsMessageProcessor.constructMessageChannel(NioTlsMessageProcessor.java:89)
    at android.gov.nist.javax.sip.stack.NioTcpMessageProcessor.createMessageChannel(NioTcpMessageProcessor.java:434)
    at android.gov.nist.javax.sip.stack.NioTcpMessageProcessor.createMessageChannel(NioTcpMessageProcessor.java:458)
    at android.gov.nist.javax.sip.stack.SIPTransactionStack.createMessageChannel(SIPTransactionStack.java:1776)
    at android.gov.nist.javax.sip.SipProviderImpl.createClientTransaction(SipProviderImpl.java:389)
    at android.gov.nist.javax.sip.SipProviderImpl.getNewClientTransaction(SipProviderImpl.java:455)
    at org.restcomm.android.sdk.SignalingClient.JainSipClient.JainSipClient.jainSipClientRegister(JainSipClient.java:531)
    at org.restcomm.android.sdk.SignalingClient.JainSipClient.JainSipJob$JainSipFsm.process(JainSipJob.java:657)
    at org.restcomm.android.sdk.SignalingClient.JainSipClient.JainSipJob.startFsm(JainSipJob.java:766)
    at org.restcomm.android.sdk.SignalingClient.JainSipClient.JainSipJobManager.add(JainSipJobManager.java:53)
    at org.restcomm.android.sdk.SignalingClient.JainSipClient.JainSipJobManager.add(JainSipJobManager.java:61)
    at org.restcomm.android.sdk.SignalingClient.JainSipClient.JainSipClient.onConnectivityChange(JainSipClient.java:886)
    at org.restcomm.android.sdk.SignalingClient.JainSipClient.JainSipNotificationManager.onReceive(JainSipNotificationManager.java:132)
    at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:866)
    ... 4 more
```

Can't really figure out what is going on here other than the fact that we recently changed the Message Channel to NIO. Let's keep that in mind

**Comment by atsakiridis** [comment]
No longer reproducible
