### ISSUE TITLE
setBackgroundDrawable crashes cause it's called on null pointer

### ISSUE THREAD

**Issue by atsakiridis** [RestComm/restcomm-android-sdk#450]
Got this in TF, although I can't reproduce it myself. Wondering if it has something to do with the different theme used for messages screen

Here's the stacktrace:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.app.ActionBar.setBackgroundDrawable(android.graphics.drawable.Drawable)' on a null object reference
	at org.restcomm.android.olympus.MessageActivity.handleMessage(MessageActivity.java:212)
	at org.restcomm.android.olympus.MessageActivity.onServiceConnected(MessageActivity.java:194)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1275)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1292)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:6134)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
```

**Comment by atsakiridis** [comment]
Couldn't reproduce this to be able to verify if this actually fixes it. Let's keep an eye for this.
