### ISSUE TITLE
Investigate Olympus .apk crash

### ISSUE THREAD

**Issue by atsakiridis** [RestComm/restcomm-android-sdk#454]
Testfairy session: https://telestax.testfairy.com/projects/1897533-restcommolympus/builds/4635482/sessions/20

Stacktrace:
```
java.lang.RuntimeException: Unable to instantiate service org.restcomm.android.sdk.RCDevice: java.lang.IllegalAccessException: void org.restcomm.android.sdk.RCDevice.<init>() is not accessible from java.lang.Class<android.app.ActivityThread>
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3047)
	at android.app.ActivityThread.-wrap4(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1571)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:5728)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
Caused by: java.lang.IllegalAccessException: void org.restcomm.android.sdk.RCDevice.<init>() is not accessible from java.lang.Class<android.app.ActivityThread>
	at java.lang.Class.newInstance(Native Method)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3044)
	... 8 more
```

**Comment by atsakiridis** [comment]
No longer reproducible
