### ISSUE TITLE
Failed to authenticate after max attempts

### ISSUE THREAD

**Issue by atsakiridis** [RestComm/restcomm-android-sdk#455]
Test Fairy session [here](https://telestax.testfairy.com/projects/1897533-restcommolympus/builds/4635482/sessions/58)

Stacktrace:

java.lang.RuntimeException: Failed to authenticate after max attempts
	at org.restcomm.android.sdk.SignalingClient.JainSipClient.JainSipClient.jainSipAuthenticate(JainSipClient.java:635)
	at org.restcomm.android.sdk.SignalingClient.JainSipClient.JainSipCall.processResponse(JainSipCall.java:437)
	at org.restcomm.android.sdk.SignalingClient.JainSipClient.JainSipClient$3.run(JainSipClient.java:768)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by atsakiridis** [comment]
Based on logs we shouldn't be getting such a behavior. For the max attempts error to occur Restcomm needs to challenge the same request more than 3 times with Proxy Authentication required, which isn't the case. What happens here is that we have 3 occurrences of the following flow, with register-refresh interval:
1. Send REGISTER
2. Get Proxy Auth
3. Send REGISTER with creds
4. Get FORBIDDEN

Which is legit and shouldn't be causing any exception. 

I also tried locally the exact same thing to see if there's any case that the 3 different register jobs got messed up somehow, but it seems to be working fine for me.

Let's leave code as is for now to be able to monitor until we get more info. One we figure that out we should remove the Runtime Exception and probably just issue an error (which will be mean an issue with Restcomm probably, i.e. challenging for creds ever after it has received them)

**Comment by atsakiridis** [comment]
No longer reproducible
