### ISSUE TITLE
Call timer not canceled if call is canceled before call setup is complete

### ISSUE THREAD

**Issue by atsakiridis** [RestComm/restcomm-android-sdk#621]
Here's an analysis of the issue:
- Android Olympus receives a call (I think from another Android Olympus)
- While candidates are still gathering the call is hung up from the other side (not sure why we get BYE instead of CANCEL we need to check that)
- Call is disconnected
- After a while we get a timeout to our handler ("onCallTimeout")
- After a while Android Olympus makes a call and while the webrtc processing starts to generated SDP the App crashes

Even though it's not clear what the root cause is, one issue we have is that the timer is not cancelled when the first call is disconnected. This could cause an exception due to disconnect logic being called again (due to the time out). Still, the exception seems to happen later. So we need to try to reproduce.

For sure we need to cancel timeoutHandler in such events to avoid the exception.

With this opportunity let's also revisit the whole time logic because I have the impression there is room for improvement there (I see to recall some issues with it in the past)

Here's Test Fairy [session](https://telestax.testfairy.com/projects/3369662-restcommolympus/builds/5916479/sessions/59?source=email-crash)

And here's the reported stack trace:
```
java.lang.RuntimeException: No RCConnection exists to handle message with jobid: 1498095728050
	at org.restcomm.android.sdk.RCDevice.getConnectionByJobId(RCDevice.java:915)
	at org.restcomm.android.sdk.SignalingClient.SignalingClient.handleMessage(SignalingClient.java:351)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6247)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
```

**Comment by atsakiridis** [comment]
Bumping up priority as we get this a lot for the latest official version

**Comment by atsakiridis** [comment]
Another occurrence of this issue is [this](https://telestax.testfairy.com/projects/3369662-restcommolympus/builds/5916479/sessions/261?source=email-crash), which is different than the one in the description though. 

Scenario:
- Bob calls +1234 RC App
- App answers 
- Bob receives 200 OK but somehow gets stuck

Analysis:

- Weird thing is that although 200 OK is received properly for the INVITE, onCallOutgoingConnected is never called for RCConnection
- Based on the stack trace `CALL_LOCAL_DISCONNECT_EVENT` event arrives on UI thread, which can only be result of either BYE called in the caller or CANCEL from the caller, but neither of them seem to have been triggered by the user based on logs!

The only explanation is that some logs are somehow missing and mess things up. Need to investigate more occurrences of this issue

**Comment by atsakiridis** [comment]
After investigation seems there's a bigger issue with how JAIN SIP resources are handled that we need to address and due to which most of these crashes happen: #637

**Comment by atsakiridis** [comment]
For this issue I'll be fixing the timer issue and we can monitor how it behaves in the futures
