### ISSUE TITLE
java.security.NoSuchAlgorithmException: The BC provider no longer provides an implementation for KeyPairGenerator.EC

### ISSUE THREAD

**Issue by tahirjilani** [RestComm/restcomm-android-sdk#855]
Starting from Android P it gives error:
java.security.NoSuchAlgorithmException: The BC provider no longer provides an implementation for KeyPairGenerator.EC

And then app crashes.

Crash logs are:

E/AndroidRuntime: FATAL EXCEPTION: signaling-handler-thread
    Process: com.medocity.doctor, PID: 27983
    java.lang.NullPointerException
        at java.util.Hashtable.put(Hashtable.java:461)
        at java.util.Properties.setProperty(Properties.java:161)
        at org.restcomm.android.sdk.SignalingClient.JainSipClient.JainSipSecurityHelper.setProperties(JainSipSecurityHelper.java:220)
        at org.restcomm.android.sdk.SignalingClient.JainSipClient.JainSipClient.open(JainSipClient.java:208)
        at org.restcomm.android.sdk.SignalingClient.SignalingHandler.handleMessage(SignalingHandler.java:76)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)

**Comment by tahirjilani** [comment]
One can find the fix for this issue at https://github.com/RestComm/restcomm-android-sdk/pull/856/commits/ae64637b452a47a4cd5b113df8c2937fb72c41fd
Thanks.
